blank_issues_enabled: false
contact_links:
  - name: CSLAND.FUN Support
    url: https://cslang.fun/support
    about: –ï—Å–ª–∏ —á—Ç–æ-—Ç–æ –ø–æ—à–ª–æ —Å–æ–≤—Å–µ–º –Ω–µ —Ç–∞–∫ ‚Äî –∑–∞—Ö–æ–¥–∏—Ç–µ –Ω–∞ —Å–∞–π—Ç üòä
